spring:
  config:
    import: optional:file:.env.test[.properties]
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomTestPostgreSQLDialect
custom:
  site:
    cookieDomain: "${custom.test.cookieDomain}"
    frontUrl: "${custom.test.frontUrl}"
    backUrl: "${custom.test.backUrl}"
    dbHost: "${custom.test.dbHost}"
    dbName: "${custom.test.dbName}"
    redisHost: "${custom.test.redisHost}"
    redisDatabase: "${custom.test.redisDatabase}"